### ISSUE TITLE
[1.19.2] Crafting conflict between TF wood trapdoors and wood plank walls

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/Do-I-am-Ornament#2]
Mod version: 1.19.2-1.1.0

Like the title says, the crafting recipe for tf trapdoors (3x2 of planks in a crafting bench) conflicts with the recipe for plank walls

**Comment by Andromander** [comment]
Looks like I addressed this for the 1.19.3 port. They use Slabs now.
